reoxidant/practice-swift

playground/Tuples.playground/Contents.swift, playground/Tuples.playground/contents.xcplayground
practice with tuples, also complete all test in this lesson
close issue #37
complete after 1:20 min
=> update #37 issues

playground/Array.playground/Contents.swift, playground/Array.playground/contents.xcplayground, playground/Array.playground/timeline.xctimeline
Complete test on knowledge and complete my tasks, and practice in arrays
Closes #39 issue
=> close #39 issue

playground/SafetyAndTypeInterface.playground/Contents.swift, playground/SafetyAndTypeInterface.playground/contents.xcplayground
Reading and practice with typing values and output typing
=> finish my #227 issue

playground/OptionalsTypes.playground/Contents.swift, playground/OptionalsTypes.playground/contents.xcplayground
reading content documentnation of swift by recomdation stanford. Readed optional path and some practice, close #230 issue
=> finish #230 issue

playground/docCoutingCharacters.playground/Contents.swift, playground/docCoutingCharacters.playground/contents.xcplayground
Practice 20 min reading documentation
Close #233 issue
=> finish #233 issue

playground/docControlTransferStatements.playground/Contents.swift, playground/docControlTransferStatements.playground/contents.xcplayground
finish my practice with control tansfer statements.
close #239 issue
=> close #239 issue

playground/docConditionalStatements.playground/Contents.swift, playground/docConditionalStatements.playground/contents.xcplayground
practice working and reading swift doc
close #16
=> finish my #16 issue

playground/docComparingClassAndStructure.playground/Contents.swift, playground/docComparingClassAndStructure.playground/contents.xcplayground
finish my reading and practice on #243 issue, close #243 issue
=> Finish #243 issue

playground/docProperties.playground/Contents.swift, playground/docProperties.playground/contents.xcplayground
finish my work and practice with computed properties
close #246 issue
=> update #246 issue

playground/docStoredProperties.playground/Contents.swift, playground/docStoredProperties.playground/contents.xcplayground
close #249 issue, finish my practice theme
=> #249 issue

playground/docSemicolon.playground/Contents.swift, playground/docSemicolon.playground/contents.xcplayground
finish my reading and practice, need to close #252 issue
=> finish #252 issue

playground/docFloatingPointNumbers.playground/Contents.swift, playground/docFloatingPointNumbers.playground/contents.xcplayground
finish my reading and work on Int-float numbers
=> finish #254 issue

playground/docInitializingAnEmptyString.playground/Contents.swift, playground/docInitializingAnEmptyString.playground/contents.xcplayground
Initializing an Empty String #262 issue
=> #262 issue

playground/docWorkingWithCharacters.playground/Contents.swift, playground/docWorkingWithCharacters.playground/contents.xcplayground
Finish my reading and practice with Characters
#263 close issue
=> finish #263-issue

playground/docComparingStrings.playground/Contents.swift, playground/docComparingStrings.playground/contents.xcplayground
Finish my Reading and Working Comparing Strings. Close #264 issue.
=> finish #264-issue

playground/docNilCoalescingOperator.playground/Contents.swift, playground/docNilCoalescingOperator.playground/contents.xcplayground
Close #274 reading and practie with Nil-Coalescing Operator
=> finish #247 issue

playground/algoritmReturnReverseString.playground/Contents.swift, playground/algoritmReturnReverseString.playground/contents.xcplayground
Close practice with reversing string algoritm. Close #282 issue
=> close #282 issue

playground/algoritmStringsWithOneDifference.playground/Contents.swift, playground/algoritmStringsWithOneDifference.playground/contents.xcplayground
=> finish #286 issue

playground/docTuplesInConditionalStatements.playground/Contents.swift, playground/docTuplesInConditionalStatements.playground/contents.xcplayground
finish my reading and practice with Tuples in Conditional Statements
close #277 issue
=> finish #277-issue

playground/docBindingValuesInConditionalStatements.playground/Contents.swift, playground/docBindingValuesInConditionalStatements.playground/contents.xcplayground
=> finish #278 issue

playground/docWhereInConditionalStatements.playground/Contents.swift, playground/docWhereInConditionalStatements.playground/contents.xcplayground
Finish my practice and reading on Where in Conditional Statements
Close #279 issue
=> finish #279 issue

Playground/docClassesAndReferenceTypes.playground/Contents.swift, Playground/docClassesAndReferenceTypes.playground/contents.xcplayground
Finish my reading and working with class and his reference
Close #29 issue
=> finish #29 issue

Playground/docEnumeration.playground/Contents.swift, Playground/docEnumeration.playground/contents.xcplayground
finish my reading and practice with Enumerations
Close #35 issue
=> finish #35 issue

Playground/docDictionary.playground/Contents.swift, Playground/docDictionary.playground/contents.xcplayground
Finish reading and practice with Dictionary
Close #36 issue
=> finish #36 issue

Playground/docClosuresAreReferenceTypes.playground/Contents.swift, Playground/docClosuresAreReferenceTypes.playground/contents.xcplayground
Finish reading and working with closure on reference types
Close #255
=> finish #255 issue

Playgrounds/The Basics/docAssertions.playground/Contents.swift, Playgrounds/The Basics/docAssertions.playground/contents.xcplayground, Playgrounds/The Basics/docComments.playground/Contents.swift, Playgrounds/The Basics/docComments.playground/contents.xcplayground
Finish my reading and practice Assertions and Comments topics
=> update #347 issue

Playgrounds/Basic Operators/docLogicalOperators.playground/Contents.swift, Playgrounds/Basic Operators/docLogicalOperators.playground/contents.xcplayground, Playgrounds/Basic Operators/docTernaryConditionalOperator.playground/Contents.swift, Playgrounds/Basic Operators/docTernaryConditionalOperator.playground/contents.xcplayground
Practice and reading Logical Operators and  Ternary Conditional Operator topics
Close #348 issue and all section
=> update #348 issue

Playgrounds/Inheritance/docOverriding.playground/Contents.swift, Playgrounds/Inheritance/docOverriding.playground/contents.xcplayground
=> practice with Inheritance in Documentation

Playgrounds/Strings and Characters/docUnicode.playground/Contents.swift, Playgrounds/Strings and Characters/docUnicode.playground/contents.xcplayground, Playgrounds/Strings and Characters/docUnicodeRepresentationsOfStrings.playground/Contents.swift, Playgrounds/Strings and Characters/docUnicodeRepresentationsOfStrings.playground/contents.xcplayground
=> Documentation

Projects/HttpRequests/HttpRequests.xcodeproj/project.pbxproj, Projects/HttpRequests/HttpRequests/Info.plist, Projects/HttpRequests/HttpRequests/Model/Album.swift, Projects/HttpRequests/HttpRequests/Model/NetworkManager.swift, Projects/HttpRequests/HttpRequests/Support Files/AppDelegate.swift, Projects/HttpRequests/HttpRequests/Support Files/Assets.xcassets/AccentColor.colorset/Contents.json, Projects/HttpRequests/HttpRequests/Support Files/Assets.xcassets/AppIcon.appiconset/Contents.json, Projects/HttpRequests/HttpRequests/Support Files/Assets.xcassets/Contents.json, Projects/HttpRequests/HttpRequests/Support Files/Base.lproj/LaunchScreen.storyboard, Projects/HttpRequests/HttpRequests/Support Files/Base.lproj/Main.storyboard, Projects/HttpRequests/HttpRequests/Support Files/SceneDelegate.swift, Projects/HttpRequests/HttpRequests/View/CollectionViewCell.swift, Projects/HttpRequests/HttpRequests/ViewController/CollectionViewController.swift, Projects/SpringApp/SpringApp.xcodeproj/project.pbxproj, Projects/SpringApp/SpringApp/Animation.swift, Projects/SpringApp/SpringApp/ViewController.swift
=> corrected code in SpringApp and created HttpRequest app

Playgrounds/Algoritms/algoritmTestCases.playground/Contents.swift, Projects/ContactsApp/ContactsApp.xcodeproj/project.pbxproj, Projects/ContactsApp/ContactsApp/Info.plist, Projects/ContactsApp/ContactsApp/Model/Contact.swift, Projects/ContactsApp/ContactsApp/Resources/Assets.xcassets/AccentColor.colorset/Contents.json, Projects/ContactsApp/ContactsApp/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json, Projects/ContactsApp/ContactsApp/Resources/Assets.xcassets/Contents.json, Projects/ContactsApp/ContactsApp/Services/StorageManager.swift, Projects/ContactsApp/ContactsApp/Storyboards/Base.lproj/LaunchScreen.storyboard, Projects/ContactsApp/ContactsApp/Storyboards/Base.lproj/Main.storyboard, Projects/ContactsApp/ContactsApp/Supporting Files/AppDelegate.swift, Projects/ContactsApp/ContactsApp/Supporting Files/SceneDelegate.swift, Projects/ContactsApp/ContactsApp/ViewControllers/NewContactViewController.swift, Projects/ContactsApp/ContactsApp/ViewControllers/ViewController.swift
=> Saved data used UserDefaults and file plist and practiced with Leetcode

Projects/SliderColorsSwiftUI/SliderColorsSwiftUI.xcodeproj/project.pbxproj, Projects/SliderColorsSwiftUI/SliderColorsSwiftUI/Assets.xcassets/AccentColor.colorset/Contents.json, Projects/SliderColorsSwiftUI/SliderColorsSwiftUI/Assets.xcassets/AppIcon.appiconset/Contents.json, Projects/SliderColorsSwiftUI/SliderColorsSwiftUI/Assets.xcassets/Contents.json, Projects/SliderColorsSwiftUI/SliderColorsSwiftUI/ColorView.swift, Projects/SliderColorsSwiftUI/SliderColorsSwiftUI/ContentView.swift, Projects/SliderColorsSwiftUI/SliderColorsSwiftUI/Preview Content/Preview Assets.xcassets/Contents.json, Projects/SliderColorsSwiftUI/SliderColorsSwiftUI/SliderColorView.swift, Projects/SliderColorsSwiftUI/SliderColorsSwiftUI/SliderColorsSwiftUIApp.swift, Projects/SliderColorsSwiftUI/SliderColorsSwiftUI/TextFieldColorView.swift, Projects/TrafficLightsSwiftUI/TrafficLightsSwiftUI.xcodeproj/project.pbxproj, Projects/TrafficLightsSwiftUI/TrafficLightsSwiftUI/Assets.xcassets/AccentColor.colorset/Contents.json, Projects/TrafficLightsSwiftUI/TrafficLightsSwiftUI/Assets.xcassets/AppIcon.appiconset/Contents.json, Projects/TrafficLightsSwiftUI/TrafficLightsSwiftUI/Assets.xcassets/Contents.json, Projects/TrafficLightsSwiftUI/TrafficLightsSwiftUI/ColorCircle.swift, Projects/TrafficLightsSwiftUI/TrafficLightsSwiftUI/ContentView.swift, Projects/TrafficLightsSwiftUI/TrafficLightsSwiftUI/Preview Content/Preview Assets.xcassets/Contents.json, Projects/TrafficLightsSwiftUI/TrafficLightsSwiftUI/ToggleColorButton.swift, Projects/TrafficLightsSwiftUI/TrafficLightsSwiftUI/TrafficLightsSwiftUIApp.swift
=> Practiced with SwiftUI, created the LightTraffic and SliderColors projects

Projects/TimeCounter/TimeCounter.xcodeproj/project.pbxproj, Projects/TimeCounter/TimeCounter/Assets.xcassets/AccentColor.colorset/Contents.json, Projects/TimeCounter/TimeCounter/Assets.xcassets/AppIcon.appiconset/Contents.json, Projects/TimeCounter/TimeCounter/Assets.xcassets/Contents.json, Projects/TimeCounter/TimeCounter/Model/AppStorageManager.swift, Projects/TimeCounter/TimeCounter/Model/StorageManager.swift, Projects/TimeCounter/TimeCounter/Model/TimeCounter.swift, Projects/TimeCounter/TimeCounter/Model/UserManager.swift, Projects/TimeCounter/TimeCounter/Preview Content/Preview Assets.xcassets/Contents.json
=> initialized the TimeCounter project

Playgrounds/Algoritms/algoritmTestCases.playground/Contents.swift, Projects/TimeCounter/TimeCounter/ButtonAppearanceModifier.swift, Projects/TimeCounter/TimeCounter/ButtonView.swift, Projects/TimeCounter/TimeCounter/RegisterView.swift, Projects/TimeCounter/TimeCounter/StartedView.swift, Projects/TimeCounter/TimeCounter/TimeCounterApp.swift, Projects/TimeCounter/TimeCounter/TimerView.swift
=> Practiced with the leetcode algorithms and added views to TimeCounter

Playgrounds/Algoritms/algoritmTestCases.playground/Contents.swift, Playgrounds/Concurrency/grandCentralDispatch.playground/Contents.swift, Playgrounds/Concurrency/grandCentralDispatch.playground/contents.xcplayground, Playgrounds/Concurrency/grandCentralDispatch.playground/playground.xcworkspace/contents.xcworkspacedata
=> Practiced the GCD race condition cases and async, sync queues

Projects/GuessTheNumber/GuessTheNumber.xcodeproj/project.pbxproj, Projects/GuessTheNumber/GuessTheNumber/Assets.xcassets/AccentColor.colorset/Contents.json, Projects/GuessTheNumber/GuessTheNumber/Assets.xcassets/AppIcon.appiconset/Contents.json, Projects/GuessTheNumber/GuessTheNumber/Assets.xcassets/Contents.json, Projects/GuessTheNumber/GuessTheNumber/ButtonView.swift, Projects/GuessTheNumber/GuessTheNumber/ContentView.swift, Projects/GuessTheNumber/GuessTheNumber/GuessTheNumberApp.swift, Projects/GuessTheNumber/GuessTheNumber/Preview Content/Preview Assets.xcassets/Contents.json, Projects/GuessTheNumber/GuessTheNumber/SliderView.swift, Projects/GuessTheNumber/GuessTheNumber/SliderViewRepresentable.swift
=> Initialized project GuessTheNumber and added views

Playgrounds/Concurrency/EnvironmentGCD.playground/Contents.swift, Playgrounds/Concurrency/EnvironmentGCD.playground/contents.xcplayground, Playgrounds/Concurrency/EnvironmentGCD.playground/playground.xcworkspace/contents.xcworkspacedata, Projects/ContactListSwiftUI/ContactListSwiftUI.xcodeproj/project.pbxproj, Projects/ContactListSwiftUI/ContactListSwiftUI/Assets.xcassets/AccentColor.colorset/Contents.json, Projects/ContactListSwiftUI/ContactListSwiftUI/Assets.xcassets/AppIcon.appiconset/Contents.json, Projects/ContactListSwiftUI/ContactListSwiftUI/Assets.xcassets/Contents.json, Projects/ContactListSwiftUI/ContactListSwiftUI/Preview Content/Preview Assets.xcassets/Contents.json
=> Practiced with GCD environment

Playgrounds/Algoritms/algoritmTestCases.playground/Contents.swift, Projects/ContactListSwiftUI/ContactListSwiftUI/Model/DataManager.swift, Projects/ContactListSwiftUI/ContactListSwiftUI/Model/Person.swift
=> Added the model data for persons on ContactList project

Playgrounds/Concurrency/EnvironmentGCD.playground/Contents.swift, Projects/ContactListSwiftUI/ContactListSwiftUI/ContactDetailList.swift, Projects/ContactListSwiftUI/ContactListSwiftUI/ContactInfo/ContactInfo.swift, Projects/ContactListSwiftUI/ContactListSwiftUI/ContactInfo/ContactInfoRow.swift, Projects/ContactListSwiftUI/ContactListSwiftUI/ContactList.swift, Projects/ContactListSwiftUI/ContactListSwiftUI/ContactListSwiftUIApp.swift, Projects/ContactListSwiftUI/ContactListSwiftUI/ContentView.swift
=> Added views to the ContactList project

Playgrounds/Concurrency/DispatchWorkItem.playground/Contents.swift, Playgrounds/Concurrency/DispatchWorkItem.playground/contents.xcplayground, Playgrounds/Concurrency/DispatchWorkItem.playground/playground.xcworkspace/contents.xcworkspacedata, Playgrounds/Concurrency/DispatchWorkItem.playground/timeline.xctimeline, Projects/AwardsCollectionApp/AwardsCollectionApp.xcodeproj/project.pbxproj, Projects/AwardsCollectionApp/AwardsCollectionApp/Info.plist, Projects/AwardsCollectionApp/AwardsCollectionApp/Preview Content/Preview Assets.xcassets/Contents.json, Projects/AwardsCollectionApp/AwardsCollectionApp/Supporting FIles/Assets.xcassets/AppIcon.appiconset/Contents.json, Projects/AwardsCollectionApp/AwardsCollectionApp/Supporting FIles/Assets.xcassets/Contents.json, Projects/AwardsCollectionApp/AwardsCollectionApp/Supporting FIles/Base.lproj/LaunchScreen.storyboard
=> initialized and created the AwardsCollectionApp project

Playgrounds/Concurrency/DispatchGroup.playground/Pages/GroupAsyncTasks.xcplaygroundpage/Contents.swift, Playgrounds/Concurrency/DispatchGroup.playground/Pages/GroupAsyncTasks.xcplaygroundpage/timeline.xctimeline, Playgrounds/Concurrency/DispatchGroup.playground/Pages/GroupSyncTasks.xcplaygroundpage/Contents.swift, Playgrounds/Concurrency/DispatchGroup.playground/contents.xcplayground, Playgrounds/Concurrency/DispatchGroup.playground/playground.xcworkspace/contents.xcworkspacedata, Playgrounds/Concurrency/ThreadSafe.playground/Contents.swift, Playgrounds/Concurrency/ThreadSafe.playground/contents.xcplayground, Playgrounds/Concurrency/ThreadSafe.playground/playground.xcworkspace/contents.xcworkspacedata
=> practiced with the DispatchGroup queue and the ThreadSafe queue

Projects/AwardsCollectionApp/AwardsCollectionApp/Model/Award.swift, Projects/AwardsCollectionApp/AwardsCollectionApp/Shapes/CurvesView.swift, Projects/AwardsCollectionApp/AwardsCollectionApp/Shapes/GradientRectangles.swift, Projects/AwardsCollectionApp/AwardsCollectionApp/Shapes/PathView.swift, Projects/AwardsCollectionApp/AwardsCollectionApp/Shapes/SunView.swift
=> Added the Shapes views and the Award model in the AwardsCollectionApp

Projects/AwardsCollectionApp/AwardsCollectionApp/Views/AwardsCollectionApp.swift, Projects/AwardsCollectionApp/AwardsCollectionApp/Views/ContentView.swift, Projects/AwardsCollectionApp/AwardsCollectionApp/Views/CustomGridView.swift, Projects/AwardsCollectionApp/AwardsCollectionApp/Views/CustomView.swift, Projects/AwardsCollectionApp/AwardsCollectionApp/Views/ShapesView.swift, Projects/AwardsCollectionApp/AwardsCollectionApp/Views/TabViews.swift
=> added the shapes views with animation and the grid view

Projects/ContactListMVP/ContactListMVP/ContactListModule/Model/ContactManager.swift, Projects/ContactListMVP/ContactListMVP/ContactListModule/Presenter/ContactListPresenter.swift, Projects/ContactListMVP/ContactListMVP/ContactListModule/Views/ContactListViewController.swift, Projects/ContactListMVP/ContactListMVP/DetailModule/Presenter/DetailPresenter.swift, Projects/ContactListMVP/ContactListMVP/DetailModule/Views/DetailViewController.swift, Projects/ContactListMVP/ContactListMVP/DetailModule/Views/DetailViewController.xib
=> added new methods in ContactListModule for router and initialized the DetailModule

Projects/ProductListMVVM/ProductListMVVM.xcodeproj/project.pbxproj, Projects/ProductListMVVM/ProductListMVVM/DetailProductModule/DetailProductViewController.swift, Projects/ProductListMVVM/ProductListMVVM/DetailProductModule/DetailProductViewModel.swift, Projects/ProductListMVVM/ProductListMVVM/Models/Product.swift, Projects/ProductListMVVM/ProductListMVVM/ProductListModule/ProductCellModule/ProductCellViewModel.swift, Projects/ProductListMVVM/ProductListMVVM/ProductListModule/ProductCellModule/ProductTableViewCell.swift, Projects/ProductListMVVM/ProductListMVVM/ProductListModule/ProductListTableViewController.swift, Projects/ProductListMVVM/ProductListMVVM/ProductListModule/ProductListViewModel.swift, Projects/ProductListMVVM/ProductListMVVM/Resources/Assets.xcassets/AccentColor.colorset/Contents.json, Projects/ProductListMVVM/ProductListMVVM/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json, Projects/ProductListMVVM/ProductListMVVM/Resources/Assets.xcassets/Contents.json, Projects/ProductListMVVM/ProductListMVVM/Services/DataManager.swift, Projects/ProductListMVVM/ProductListMVVM/Services/NetworkManager.swift, Projects/ProductListMVVM/ProductListMVVM/Storyboards/Base.lproj/LaunchScreen.storyboard, Projects/ProductListMVVM/ProductListMVVM/Storyboards/Base.lproj/Main.storyboard, Projects/ProductListMVVM/ProductListMVVM/Supporting Files/AppDelegate.swift, Projects/ProductListMVVM/ProductListMVVM/Supporting Files/Info.plist, Projects/ProductListMVVM/ProductListMVVM/Supporting Files/SceneDelegate.swift
=> created the ProductListMVVM project

Projects/ContactListMVP/ContactListMVP.xcodeproj/project.pbxproj, Projects/ContactListMVP/ContactListMVPTests/ContactListPresenterTests.swift, Projects/ContactListMVP/ContactListMVPTests/RouterTests.swift, Projects/ContactListMVP/ContactListMVPUITests/ContactListMVPUITests.swift, Projects/ContactListMVP/ContactListMVPUITests/ContactListMVPUITestsLaunchTests.swift
=>  created the unit tests an UI tests in ContactListMVP project

Projects/ProductListSwiftUI/ProductListSwiftUI.xcodeproj/project.pbxproj, Projects/ProductListSwiftUI/ProductListSwiftUI/Assets.xcassets/AccentColor.colorset/Contents.json, Projects/ProductListSwiftUI/ProductListSwiftUI/Assets.xcassets/AppIcon.appiconset/Contents.json, Projects/ProductListSwiftUI/ProductListSwiftUI/Assets.xcassets/Contents.json, Projects/ProductListSwiftUI/ProductListSwiftUI/Models/Product.swift, Projects/ProductListSwiftUI/ProductListSwiftUI/Preview Content/Preview Assets.xcassets/Contents.json
=> initialized the ProductListSwiftUI project and added Product model

Projects/HowOldAmI/HowOldAmI.xcodeproj/project.pbxproj
=> refactor(HowOldAmI): renamed path to info.plist

Projects/ViperModule/ViperModule.xcodeproj/project.pbxproj, Projects/ViperModule/ViperModule/AppDelegate.swift, Projects/ViperModule/ViperModule/Assets.xcassets/AccentColor.colorset/Contents.json, Projects/ViperModule/ViperModule/Assets.xcassets/AppIcon.appiconset/Contents.json, Projects/ViperModule/ViperModule/Assets.xcassets/Contents.json, Projects/ViperModule/ViperModule/Base.lproj/LaunchScreen.storyboard, Projects/ViperModule/ViperModule/Base.lproj/Main.storyboard, Projects/ViperModule/ViperModule/Greeting/GreetingAssembly.swift, Projects/ViperModule/ViperModule/Greeting/GreetingInteractor.swift, Projects/ViperModule/ViperModule/Greeting/GreetingPresenter.swift, Projects/ViperModule/ViperModule/Greeting/GreetingViewController.swift, Projects/ViperModule/ViperModule/Info.plist, Projects/ViperModule/ViperModule/Person.swift, Projects/ViperModule/ViperModule/SceneDelegate.swift
=> Created the ViperModule project

Projects/CollectionViewInsideTableView/CollectionViewInsideTableView/Models/CollectionViewCellModel.swift, Projects/CollectionViewInsideTableView/CollectionViewInsideTableView/Models/Colors.swift, Projects/CollectionViewInsideTableView/CollectionViewInsideTableView/Models/TableViewCellModel.swift, Projects/CollectionViewInsideTableView/CollectionViewInsideTableView/Views/CollectionViewCell/CollectionViewCell.swift, Projects/CollectionViewInsideTableView/CollectionViewInsideTableView/Views/CollectionViewCell/CollectionViewCell.xib
=> created Models and CollectionViews 

Projects/CollectionViewInsideTableView/CollectionViewInsideTableView/Views/DetailsViewController.swift, Projects/CollectionViewInsideTableView/CollectionViewInsideTableView/Views/TableViewCell/TableViewCell.swift, Projects/CollectionViewInsideTableView/CollectionViewInsideTableView/Views/TableViewCell/TableViewCell.xib, Projects/CollectionViewInsideTableView/CollectionViewInsideTableView/Views/ViewController.swift
=> Created the TableViewCell and MainViewController

Projects/RxSwiftApp/Podfile, Projects/RxSwiftApp/Podfile.lock, Projects/RxSwiftApp/RxSwiftApp.xcodeproj/project.pbxproj, Projects/RxSwiftApp/RxSwiftApp.xcworkspace/contents.xcworkspacedata, Projects/RxSwiftApp/RxSwiftApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Projects/RxSwiftApp/RxSwiftApp/AppDelegate.swift, Projects/RxSwiftApp/RxSwiftApp/Assets.xcassets/AccentColor.colorset/Contents.json, Projects/RxSwiftApp/RxSwiftApp/Assets.xcassets/AppIcon.appiconset/Contents.json, Projects/RxSwiftApp/RxSwiftApp/Assets.xcassets/Contents.json, Projects/RxSwiftApp/RxSwiftApp/Base.lproj/LaunchScreen.storyboard, Projects/RxSwiftApp/RxSwiftApp/Base.lproj/Main.storyboard, Projects/RxSwiftApp/RxSwiftApp/Info.plist, Projects/RxSwiftApp/RxSwiftApp/SceneDelegate.swift, Projects/RxSwiftApp/RxSwiftApp/ViewController.swift
=> Initialized RxSwiftApp and created main realization

Projects/MedalCount/MedalCount/Base.lproj/Main.storyboard, Projects/MedalCount/MedalCount/Controllers/MainViewController.swift, Projects/MedalCount/MedalCount/Model/Games.swift
=> Created Main storyboard, MainViewController and Games model

Projects/MedalCount/MedalCount/Controllers/MedalCountViewController.swift, Projects/MedalCount/MedalCount/Model/GamesDataStore.swift, Projects/MedalCount/MedalCount/Model/MedalWinner.swift, Projects/MedalCount/MedalCount/Presentation/SlideInPresentationAnimator.swift
=> Created GamesDataStore, MedalWinner models and MedalCountViewController

Projects/MedalCount/MedalCount/Presentation/SlideInPresentationController.swift, Projects/MedalCount/MedalCount/Presentation/SlideInPresentationManager.swift, Projects/MedalCount/MedalCount/Views/GamesTableViewCell.swift, Projects/Notifications/Notifications/GoogleService-Info.plist
=> Created UIPresentationController, PresentationManager and GamesTableViewCell

Projects/Notifications/NotificationContent/Base.lproj/MainInterface.storyboard, Projects/Notifications/NotificationContent/Info.plist, Projects/Notifications/NotificationContent/NotificationViewController.swift, Projects/Notifications/NotificationService/Info.plist, Projects/Notifications/NotificationService/NotificationService.swift
=> Created the Notification service and the Notification content

Projects/Animations/SavannaTours/SavannaTours.xcodeproj/project.pbxproj, Projects/Animations/SavannaTours/SavannaTours.xcodeproj/project.xcworkspace/contents.xcworkspacedata, Projects/Animations/SavannaTours/SavannaTours.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Projects/Animations/SavannaTours/SavannaTours/Views/MilestonesList.swift, Projects/Animations/SavannaTours/SavannaTours/Views/TourTitle.swift
=> Created MilestonesList and TourTitle view, added project settings

Projects/Animations/SavannaTours/SavannaTours.xcodeproj/project.pbxproj, Projects/Animations/SavannaTours/Views/ContentView.swift, Projects/Animations/SavannaTours/Views/StarterView.swift, Projects/MedalCount/MedalCount.xcodeproj/project.xcworkspace/contents.xcworkspacedata, Projects/MedalCount/MedalCount.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
=> Practice with animation in SavannaTours SwiftUI project

Projects/Animations/SavannaTours/Views/ContentView.swift
=> feat(SavannaTours): created the TourTitle and Image thumb animation

Projects/Animations/SavannaTours/SavannaTours/Assets/Launch Screen.storyboard, Projects/Animations/SavannaTours/Views/ContentView.swift
=> Set centered position for views with animate effect

Projects/Animations/Spinner/Spinner.xcodeproj/project.pbxproj, Projects/Animations/Spinner/Spinner.xcodeproj/project.xcworkspace/contents.xcworkspacedata, Projects/Animations/Spinner/Spinner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Projects/Animations/Spinner/Spinner/Assets/AppDelegate.swift, Projects/Animations/Spinner/Spinner/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json, Projects/Animations/Spinner/Spinner/Assets/Assets.xcassets/Contents.json, Projects/Animations/Spinner/Spinner/Assets/Base.lproj/LaunchScreen.storyboard, Projects/Animations/Spinner/Spinner/Assets/Delay.swift, Projects/Animations/Spinner/Spinner/Assets/Info.plist, Projects/Animations/Spinner/Spinner/Assets/SceneDelegate.swift, Projects/Animations/Spinner/Spinner/SpinnerView.swift
=> Initialized Spinner project and created animation view

Projects/BullsEye/BullsEye/Base.lproj/LaunchScreen.storyboard, Projects/BullsEye/BullsEye/Base.lproj/Main.storyboard, Projects/BullsEye/BullsEye/Supporting Files/NetworkMonitor.swift
=> BullsEye: created LaunchScreen, MainScreen storyboards and NetworkMonitor class

Playgrounds/TDD/CashRegister.playground/Contents.swift, Playgrounds/TDD/CashRegister.playground/contents.xcplayground, Projects/BullsEye/BullsEye/Supporting Files/URLSessionStub.swift
=> Practiced with TDD CashRegister XCTest cases

Playgrounds/Algorithms/Introduction.playground/Contents.swift, Playgrounds/Algorithms/Introduction.playground/contents.xcplayground, Playgrounds/Algorithms/Introduction.playground/playground.xcworkspace/contents.xcworkspacedata, Projects/BullsEye/BullsEye/BullsEyeGame.swift
=> Practice with the Introduction algorithms section and created in BullsEye the game business logic

Playgrounds/Algorithms/Introduction.playground/Contents.swift, Projects/BullsEye/BullsEye/ViewController.swift
=> Practiced with Introduction algorithms section and created the BullsEye ViewController

Projects/BullsEye/BullsEyeSlowTests/BullsEyeSlowTests.swift, Projects/BullsEye/BullsEyeTests/BullsEyeTests.swift
=> BullsEye: created score games and network API unit tests

Projects/BullsEye/BullsEyeTests/BullsEyeFakeTests.swift, Projects/BullsEye/BullsEyeTests/BullsEyeMockTests.swift
=> Created the mock and fake game style tests

Playgrounds/TDD/CashRegister.playground/playground.xcworkspace/contents.xcworkspacedata, Projects/BullsEye/BullsEyeUITests/BullsEyeUITests.swift
=>  Created change the game style UI test in BullsEye and added project workspacedata in CashRegister

Playgrounds/Algorithms/BinarySearch.playground/Contents.swift, Playgrounds/Algorithms/BinarySearch.playground/contents.xcplayground, Playgrounds/Algorithms/BinarySearch.playground/playground.xcworkspace/contents.xcworkspacedata, Playgrounds/Algorithms/GeneralPurposeTree.playground/Contents.swift, Playgrounds/Algorithms/GeneralPurposeTree.playground/Sources/Helpers.swift, Playgrounds/Algorithms/GeneralPurposeTree.playground/Sources/Queue.swift, Playgrounds/Algorithms/GeneralPurposeTree.playground/Sources/TreeNode.swift, Playgrounds/Algorithms/GeneralPurposeTree.playground/contents.xcplayground, Playgrounds/Algorithms/GeneralPurposeTree.playground/playground.xcworkspace/contents.xcworkspacedata, Playgrounds/Algorithms/GeneralPurposeTree.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
=> feat(Algorithms): practised using a binary search argoritm and general purpose tree

Playgrounds/Algorithms/LinkedList.playground/Contents.swift, Playgrounds/Algorithms/LinkedList.playground/Sources/Helpers.swift, Playgrounds/Algorithms/LinkedList.playground/Sources/LinkedList.swift, Playgrounds/Algorithms/LinkedList.playground/Sources/Node.swift, Playgrounds/Algorithms/LinkedList.playground/contents.xcplayground, Playgrounds/Algorithms/LinkedList.playground/playground.xcworkspace/contents.xcworkspacedata, Playgrounds/Algorithms/LinkedList.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
=> feat(Algorithms): practised using a linked list

Playgrounds/Automatic Reference Counting/MemoryManagmentARCWeakStrongUnowned.playground/Contents.swift, Playgrounds/Collection Types/Arrays.playground/Contents.swift, Playgrounds/Concurrency/NSOperation.playground/Contents.swift
=> refactor(Playgrounds): corrected and translated code

Playgrounds/Functions/ConsoleApp.playground/Contents.swift, Playgrounds/Functions/ConsoleApp.playground/contents.xcplayground, Playgrounds/Functions/ConsoleApp.playground/playground.xcworkspace/contents.xcworkspacedata, Playgrounds/Functions/ConsoleApp.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
=> feat(Functions): practised with the console app function

Playgrounds/Collection Types/TypesOfCollections.playground/Pages/Arrays.xcplaygroundpage/Contents.swift, Playgrounds/Collection Types/TypesOfCollections.playground/Pages/Dictionary.xcplaygroundpage/Contents.swift, Playgrounds/Collection Types/TypesOfCollections.playground/Pages/ForInLoop.xcplaygroundpage/Contents.swift, Playgrounds/Collection Types/TypesOfCollections.playground/Pages/Set.xcplaygroundpage/Contents.swift, Playgrounds/Collection Types/TypesOfCollections.playground/Pages/WhileLoop.xcplaygroundpage/Contents.swift, Playgrounds/Collection Types/TypesOfCollections.playground/contents.xcplayground, Playgrounds/Collection Types/TypesOfCollections.playground/playground.xcworkspace/contents.xcworkspacedata, Playgrounds/Collection Types/TypesOfCollections.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Playgrounds/Functions/docDefiningAndCallingFunctions.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Playgrounds/Inheritance/Overriding.playground/playground.xcworkspace/contents.xcworkspacedata
=> feat(Playgrounds): practised and corrected code in folders

Playgrounds/Protocols/ClassAndProtocols.playground/Contents.swift, Playgrounds/Protocols/ClassAndProtocols.playground/contents.xcplayground, Playgrounds/Protocols/ClassAndProtocols.playground/playground.xcworkspace/contents.xcworkspacedata, Playgrounds/Protocols/ClassAndProtocols.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
=> feat(Playgrounds): practised using the Classes and Protocols

Playgrounds/Concept and Principle OOP/ConceptAndPrincipleOOP.playground/Contents.swift, Playgrounds/Concept and Principle OOP/ConceptAndPrincipleOOP.playground/contents.xcplayground, Playgrounds/Concept and Principle OOP/ConceptAndPrincipleOOP.playground/playground.xcworkspace/contents.xcworkspacedata, Playgrounds/Concept and Principle OOP/ConceptAndPrincipleOOP.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Playgrounds/Concept and Principle OOP/ConceptAndPrincipleOOP.playground/timeline.xctimeline, Playgrounds/Protocols/Protocols.playground/Contents.swift, Playgrounds/Protocols/Protocols.playground/contents.xcplayground, Playgrounds/Protocols/Protocols.playground/playground.xcworkspace/contents.xcworkspacedata, Playgrounds/Protocols/Protocols.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Playgrounds/RxSwiftPlayground/RxSwiftPlayground/AppDelegate.swift, Playgrounds/RxSwiftPlayground/RxSwiftPlayground/Assets.xcassets/AccentColor.colorset/Contents.json, Playgrounds/RxSwiftPlayground/RxSwiftPlayground/Assets.xcassets/AppIcon.appiconset/Contents.json, Playgrounds/RxSwiftPlayground/RxSwiftPlayground/Assets.xcassets/Contents.json, Playgrounds/RxSwiftPlayground/RxSwiftPlayground/Base.lproj/LaunchScreen.storyboard, Playgrounds/RxSwiftPlayground/RxSwiftPlayground/Base.lproj/Main.storyboard, Playgrounds/RxSwiftPlayground/RxSwiftPlayground/Info.plist, Playgrounds/RxSwiftPlayground/RxSwiftPlayground/RxSwiftPlayground.playground/Contents.swift, Playgrounds/RxSwiftPlayground/RxSwiftPlayground/RxSwiftPlayground.playground/Sources/SupportCode.swift, Playgrounds/RxSwiftPlayground/RxSwiftPlayground/RxSwiftPlayground.playground/contents.xcplayground, Playgrounds/RxSwiftPlayground/RxSwiftPlayground/RxSwiftPlayground.playground/playground.xcworkspace/contents.xcworkspacedata, Playgrounds/RxSwiftPlayground/RxSwiftPlayground/SceneDelegate.swift, Playgrounds/RxSwiftPlayground/RxSwiftPlayground/ViewController.swift, Playgrounds/Type Casting/TypeCasting.playground/Resources/License.txt, Playgrounds/Type Casting/TypeCasting.playground/contents.xcplayground, Playgrounds/Type Casting/TypeCasting.playground/pages/1. Exercise - Type Casting and Inspection.xcplaygroundpage/Contents.swift, Playgrounds/Type Casting/TypeCasting.playground/pages/2. App Exercise - Workout Types.xcplaygroundpage/Contents.swift, Playgrounds/Type Casting/TypeCasting.playground/playground.xcworkspace/contents.xcworkspacedata, Playgrounds/Type Casting/TypeCasting.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
=> feat(Playgrounds): practised with the RxSwift, Protocols, Type Casting and Concept and Principle OOP

Playgrounds/Functions/FunctionsInitial.playground/Pages/Closures.xcplaygroundpage/Contents.swift, Playgrounds/Functions/FunctionsInitial.playground/Pages/Functions.xcplaygroundpage/Contents.swift, Playgrounds/Functions/FunctionsInitial.playground/Pages/Nested functions.xcplaygroundpage/Contents.swift, Playgrounds/Functions/FunctionsInitial.playground/Pages/Variable parameter.xcplaygroundpage/Contents.swift, Playgrounds/Functions/FunctionsInitial.playground/contents.xcplayground, Playgrounds/Functions/FunctionsInitial.playground/playground.xcworkspace/contents.xcworkspacedata, Playgrounds/Functions/FunctionsInitial.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
=> feat(Playgrounds): practiced using the Closures and some type of functions

Playgrounds/Combine/CombiningOperators.playground/Contents.swift, Playgrounds/Combine/CombiningOperators.playground/Sources/SupportCode.swift, Playgrounds/Combine/CombiningOperators.playground/contents.xcplayground, Playgrounds/Combine/CombiningOperators.playground/playground.xcworkspace/contents.xcworkspacedata, Playgrounds/Combine/FilteringOperators.playground/Contents.swift, Playgrounds/Combine/FilteringOperators.playground/Sources/SupportCode.swift, Playgrounds/Combine/FilteringOperators.playground/contents.xcplayground, Playgrounds/Combine/FilteringOperators.playground/playground.xcworkspace/contents.xcworkspacedata
=> feat(Playground): practiced using the Combine operators

Playgrounds/Combine/Operators.playground/Contents.swift, Playgrounds/Combine/Operators.playground/Sources/SupportCode.swift, Playgrounds/Combine/Operators.playground/contents.xcplayground, Playgrounds/Combine/Operators.playground/playground.xcworkspace/contents.xcworkspacedata, Playgrounds/Combine/SequenceOperators.playground/Contents.swift, Playgrounds/Combine/SequenceOperators.playground/Sources/SupportCode.swift, Playgrounds/Combine/SequenceOperators.playground/contents.xcplayground, Playgrounds/Combine/SequenceOperators.playground/playground.xcworkspace/contents.xcworkspacedata
=> feat(Playgrounds): practiced using the Combine basic and sequence operators

Playgrounds/Combine/TimeManipulationOperators.playground/Pages/Collect.xcplaygroundpage/Contents.swift, Playgrounds/Combine/TimeManipulationOperators.playground/Pages/Collect.xcplaygroundpage/timeline.xctimeline, Playgrounds/Combine/TimeManipulationOperators.playground/Pages/Debounce.xcplaygroundpage/Contents.swift, Playgrounds/Combine/TimeManipulationOperators.playground/Pages/Delay.xcplaygroundpage/Contents.swift, Playgrounds/Combine/TimeManipulationOperators.playground/Pages/Delay.xcplaygroundpage/timeline.xctimeline, Playgrounds/Combine/TimeManipulationOperators.playground/Pages/MeasureInterval.xcplaygroundpage/Contents.swift, Playgrounds/Combine/TimeManipulationOperators.playground/Pages/MeasureInterval.xcplaygroundpage/timeline.xctimeline, Playgrounds/Combine/TimeManipulationOperators.playground/Pages/Throttle.xcplaygroundpage/Contents.swift, Playgrounds/Combine/TimeManipulationOperators.playground/Pages/Throttle.xcplaygroundpage/timeline.xctimeline, Playgrounds/Combine/TimeManipulationOperators.playground/Pages/Timeout.xcplaygroundpage/Contents.swift, Playgrounds/Combine/TimeManipulationOperators.playground/Pages/Timeout.xcplaygroundpage/timeline.xctimeline, Playgrounds/Combine/TimeManipulationOperators.playground/Sources/Data.swift, Playgrounds/Combine/TimeManipulationOperators.playground/Sources/DeltaTime.swift, Playgrounds/Combine/TimeManipulationOperators.playground/Sources/Model.swift, Playgrounds/Combine/TimeManipulationOperators.playground/Sources/Views.swift, Playgrounds/Combine/TimeManipulationOperators.playground/contents.xcplayground, Playgrounds/Combine/TimeManipulationOperators.playground/playground.xcworkspace/contents.xcworkspacedata, Playgrounds/Combine/TransformingOperators.playground/Contents.swift, Playgrounds/Combine/TransformingOperators.playground/Sources/SupportCode.swift, Playgrounds/Combine/TransformingOperators.playground/contents.xcplayground, Playgrounds/Combine/TransformingOperators.playground/playground.xcworkspace/contents.xcworkspacedata, Playgrounds/Combine/TransformingOperators.playground/timeline.xctimeline
=> feat(Playgrounds): practiced using the Combine transforming operators and time operators

Playgrounds/Algorithms/LinkedListChallenge.playground/Pages/Challenge 1.xcplaygroundpage/Contents.swift, Playgrounds/Algorithms/LinkedListChallenge.playground/Pages/Challenge 2.xcplaygroundpage/Contents.swift, Playgrounds/Algorithms/LinkedListChallenge.playground/Pages/Challenge 3.xcplaygroundpage/Contents.swift, Playgrounds/Algorithms/LinkedListChallenge.playground/Pages/Challenge 4.xcplaygroundpage/Contents.swift, Playgrounds/Algorithms/LinkedListChallenge.playground/Pages/Challenge 5.xcplaygroundpage/Contents.swift, Playgrounds/Algorithms/LinkedListChallenge.playground/Sources/Helpers.swift, Playgrounds/Algorithms/LinkedListChallenge.playground/Sources/LinkedList.swift, Playgrounds/Algorithms/LinkedListChallenge.playground/Sources/Node.swift, Playgrounds/Algorithms/LinkedListChallenge.playground/contents.xcplayground, Playgrounds/Algorithms/LinkedListChallenge.playground/playground.xcworkspace/contents.xcworkspacedata, Playgrounds/Algorithms/LinkedListChallenge.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Playgrounds/Combine/Subscription.playground/Pages/Intro.xcplaygroundpage/Contents.swift, Playgrounds/Combine/Subscription.playground/Pages/assign Example.xcplaygroundpage/Contents.swift, Playgrounds/Combine/Subscription.playground/Pages/assign example UIKIt.xcplaygroundpage/Contents.swift, Playgrounds/Combine/Subscription.playground/Pages/assign to.xcplaygroundpage/Contents.swift, Playgrounds/Combine/Subscription.playground/Pages/assign.xcplaygroundpage/Contents.swift, Playgrounds/Combine/Subscription.playground/Pages/breakpoint.xcplaygroundpage/Contents.swift, Playgrounds/Combine/Subscription.playground/Pages/creating Subscription.xcplaygroundpage/Contents.swift, Playgrounds/Combine/Subscription.playground/Pages/creating Subscription.xcplaygroundpage/timeline.xctimeline, Playgrounds/Combine/Subscription.playground/Pages/handleEvents.xcplaygroundpage/Contents.swift, Playgrounds/Combine/Subscription.playground/Pages/limited Subscriptions.xcplaygroundpage/Contents.swift, Playgrounds/Combine/Subscription.playground/Pages/print.xcplaygroundpage/Contents.swift, Playgrounds/Combine/Subscription.playground/Pages/receive on.xcplaygroundpage/Contents.swift, Playgrounds/Combine/Subscription.playground/Pages/subscribe on urlsession.xcplaygroundpage/Contents.swift, Playgrounds/Combine/Subscription.playground/Pages/subscribe on.xcplaygroundpage/Contents.swift, Playgrounds/Combine/Subscription.playground/Pages/subscription pattern.xcplaygroundpage/Contents.swift, Playgrounds/Combine/Subscription.playground/contents.xcplayground, Playgrounds/Combine/Subscription.playground/playground.xcworkspace/contents.xcworkspacedata
=> feat(Playgrounds): practiced using the Combine subscription and the Linked List algorithms

Playgrounds/Concurrency/OperationQueue.playground/Pages/OperationClass.xcplaygroundpage/Contents.swift, Playgrounds/Concurrency/OperationQueue.playground/contents.xcplayground, Playgrounds/Concurrency/grandCentralDispatch.playground/Contents.swift
=> feat(Playgrounds): practiced using the Concurrency GCD and Operation queue

Playgrounds/Algorithms/Stacks.playground/Contents.swift, Playgrounds/Algorithms/Stacks.playground/Sources/Helpers.swift, Playgrounds/Algorithms/Stacks.playground/Sources/Stack.swift, Playgrounds/Algorithms/Stacks.playground/contents.xcplayground, Playgrounds/Algorithms/Stacks.playground/playground.xcworkspace/contents.xcworkspacedata, Playgrounds/Algorithms/Stacks.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Playgrounds/Concurrency/CommonIssues.playground/Contents.swift, Playgrounds/Concurrency/CommonIssues.playground/contents.xcplayground, Playgrounds/Concurrency/CommonIssues.playground/playground.xcworkspace/contents.xcworkspacedata
=> feat(Playgrounds): practiced using the Concurrency common issues and the Algorithms stack
